/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject/$subjectId'
import { Route as SubjectSubjectIdTopicIdRouteImport } from './routes/subject/$subjectId/$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdTopicIdRoute = SubjectSubjectIdTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => SubjectSubjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/upload': typeof UploadRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$topicId': typeof SubjectSubjectIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/upload': typeof UploadRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$topicId': typeof SubjectSubjectIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/upload': typeof UploadRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRouteWithChildren
  '/subject/$subjectId/$topicId': typeof SubjectSubjectIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/upload'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/upload'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/upload'
    | '/subject/$subjectId'
    | '/subject/$subjectId/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  UploadRoute: typeof UploadRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId/$topicId': {
      id: '/subject/$subjectId/$topicId'
      path: '/$topicId'
      fullPath: '/subject/$subjectId/$topicId'
      preLoaderRoute: typeof SubjectSubjectIdTopicIdRouteImport
      parentRoute: typeof SubjectSubjectIdRoute
    }
  }
}

interface SubjectSubjectIdRouteChildren {
  SubjectSubjectIdTopicIdRoute: typeof SubjectSubjectIdTopicIdRoute
}

const SubjectSubjectIdRouteChildren: SubjectSubjectIdRouteChildren = {
  SubjectSubjectIdTopicIdRoute: SubjectSubjectIdTopicIdRoute,
}

const SubjectSubjectIdRouteWithChildren =
  SubjectSubjectIdRoute._addFileChildren(SubjectSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  UploadRoute: UploadRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
